spring:
  application:
    name: ai-know-engine
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/know_engine_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: know_engine
    password: know_engine
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      continue-on-error: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8010

minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: admin123456
  bucketName: know-engine
  endpoint: http://localhost:9000